### ISSUE TITLE
Табы

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#1]
Сделать четыре табы с таком порядке:
— Наблюдатель (инфа про пользователя, то, что у тебя в настройках), 
— Чеклист (название пока согласовываем), 
— Справочник, 
— СОС.

**Comment by xfyre** [comment]
реально их будет пять
- Профиль
- Наблюдатель
- Справочник
- SOS
- Отчет

**Comment by infotanka** [comment]
Давай в таком порядке:
— Профиль
— Наблюдение (вроде договорились использовать вместо «Наблюдателя»)
— Отчёт
(это всё процедура наблюдения)
— Справочник
— СОС
(а это дополнительные справочные материалы)

**Comment by xfyre** [comment]
ok, сделал
