### ISSUE TITLE
Сохранить → Готово

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#16]
В текстовых полях (например, «Данные о явке»), зачем-то появлется кнопка «Сохранить». Там нужна стандартная айфоновская клавиатура с кнопкой «Готово», которая будет выводить из режима редактирования. А можно по умолчанию показывать русскую клавиатуру? У меня почему-то английская появляется.

**Comment by xfyre** [comment]
Это невозможно по очень простой причине - для поля ввода многострочного текста кнопка "Готово" выполняет перевод строки. Для того, чтобы закрыть клавиатуру, нужна дополниетльная кнопка, возможно, ее нужно как-то переназвать, но без этого не обойтись.

**Comment by infotanka** [comment]
Я вот такой вариант клавиатуры из Сафари имею в виду: http://cinnamonthoughts.org/wp-content/pageImages/iPhone/WideMailKeyboard/WMKscreenshotLandscape.png

**Comment by xfyre** [comment]
Вот этот вот тулбар над клавиатурой - это как раз и есть keyboard accessory, который можно сделать произвольного вида. Ты хочешь чтобы он выглядел как toolbar? Понятно, что кнопок next/previous в нашей ситуации там не будет.

**Comment by infotanka** [comment]
Сейчас вроде стало ок, закрывай.

**Comment by infotanka** [comment]
А, нет, в «Данных о явке» всё та же большая странная кнопка. Хотя где-то я видела стандартный ай-осовские «Отмена» и «Сохранить» (сверху)

**Comment by xfyre** [comment]
Сверху не будет, будет над клавиатурой.

**Comment by infotanka** [comment]
Ок, но давай сделаем стандартную кнопку. Меня именно сама форма и плоскость кнопки смущает.

**Comment by xfyre** [comment]
Там иначе и не получится, если это тулбар - все будет выглядеть стандартно.

**Comment by infotanka** [comment]
Прекрасно. Тогда делай и закрывай.
