### ISSUE TITLE
Новый справочник

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#17]
Версия справочника, кажется, старая (копирайты, навигация, цветные блоки — мы всё это правили.) Извините, если это уже обсуждали.

**Comment by xfyre** [comment]
не знаю кто этим занимается, перевесил пока на Алексея

дайте нормальную версию - я поставлю

**Comment by infotanka** [comment]
Тебе нужно связаться с Сергеем Ерошенко (скайп: itechmeat). Он занимался причёсыванием справочника.

**Comment by xfyre** [comment]
залил
