### ISSUE TITLE
Кнопки «Фото» и «Видео»

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#2]
Фото нарушений (ФОТО) заменить на одну большую кнопку с подписью «Фото нарушений» прямо на ней. Аналогично с видео.

**Comment by xfyre** [comment]
метка к этой кнопке может быть не "фото нарушений" а что-то еще
поэтому лучше оставить как есть - от повторений большой беды нет

**Comment by infotanka** [comment]
Илья, а в чём пробелема подпись менять не слева от кнопки, а на самой кнопке? Зачем два элемента, когда можно обойтись одним? Это всё равно, что надпись «Нажмите на кнопку (КНОПКА)» — самой кнопки итак достаточно. 

Повторения ооочень некруто выглядят :-)

**Comment by xfyre** [comment]
Ну я подумаю как это поаккуратнее вырулить, но это и некритично, и не самое важное сейчас.

**Comment by infotanka** [comment]
Согласна, это сейчас не первый приоритет
