### ISSUE TITLE
Обязательные поля на первом экране

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#20]
На первом экране, на мой взгляд, вообще не должно быть обязательных полей.

Если официальный наблюдатель загрузил направление, мы итак знаем, как его зовут. Если он неофициальный — нам по фиг вообще. А если человек не хочет светить своё имя на сайте, так он просто туда вобьёт какую-нибудь фигню. Давай не будем его заставлять заполнять это поле. Всё равно большинство заполнит так или иначе.

Про почту вроде обуждали, что она нужна только на сулчай, если ты хочешь отслеживать свои репорты на сайте. Поэтому там лучше напистаь «Эл. почта (для отслеживания данных на сайте)» — без всяких звёздочек.

**Comment by xfyre** [comment]
ok, я это убрал в конфигурации, если захотим добавить обратно - не проблема
