### ISSUE TITLE
Переносы в списках

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#23]
В списках на первом и втором уровне некторые пункты сокращаются троеточием и теряется смысл.

Их нужно либо переносить, либо сокращать формулировки. Илья, перенос возможен? Если нет, присылай файл на правку.

Заседание и оформление протокола → Заседание и протокол — сразу можно поправить

**Comment by xfyre** [comment]
Нужно сокращать формулировки, очевидно.
Выходи в скайп, я тебе все скину.
