### ISSUE TITLE
фильтрация чеклиста в зависимости от типа участка

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#24]
Предлагаю убрать из списка данных по участкам пункт «ТИК/ИКМО» и показывать его только при добавлении участка типа «ТИК». Причём для Тика можно второй уровень вынести на первый. Но это необязательно.

**Comment by xfyre** [comment]
Я вообще собираюсь фильтровать список в зависимости от того, что выбрано - если сейчас мы на УИК, показывать пункты только про УИК, если на ТИК - то только про ТИК.

**Comment by infotanka** [comment]
Да, я так и предлагаю.

Просто про ТИК у нас один пункт на верхнем уровне, поэтому круче было бы просто второй уровень вынести наверх.

**Comment by xfyre** [comment]
будет проблематично - чеклист у нас трехуровневый и там много чего придется переделывать

**Comment by infotanka** [comment]
Ок, тогда пусть верхний уровень остаётся и называется как-нибудь
«Обработка результатов»

2012/2/18 Ilya Obshadko
reply@reply.github.com:

**Comment by xfyre** [comment]
готово
