### ISSUE TITLE
Регион

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#26]
Нужно добавить поле в «Участке». Его сейчас нигде нет.

Возможно ли прикрутить автоматическое определени?

**Comment by xfyre** [comment]
если на сервере по координатам или номеру УИК могут дать нужное значение - без вопросов

**Comment by infotanka** [comment]
Не, подожди. Регион, это же типа «Брянская обл.» — это можно просто по координатам понять. Наверняка, есть какие-то службы для этого.

**Comment by xfyre** [comment]
Может быть, и есть, но я про их существование не знаю. В любом случае, автоопределение региона по координатам - это не фоновая активность, а в приложении принципиально то, что все взаимодействие с серверной частью исключительно фоновое.

**Comment by infotanka** [comment]
Ок, значит ставь пока просто списко регионов.

2012/2/18 Ilya Obshadko
reply@reply.github.com:

**Comment by xfyre** [comment]
Каких именно? Субъектов федерации?

**Comment by infotanka** [comment]
Нужно уточнить у Лёши.

On 18 February 2012 12:33, Ilya Obshadko
reply@reply.github.com
wrote:

**Comment by xfyre** [comment]
так уточните :)

я в этом не вижу никакого смысла
если мы можем не грузить пользователя этим - не нужно его этим грузить
регион автоматически определяется по УИК-у на серверной стороне

**Comment by infotanka** [comment]
Номер уникален внутри региона, так что поле регион — обязательное.

Давай пока сделаем выбор из списка регионов, а потом прикрутим геопозиционирование. Это должно быть как-то очень просто. Может быть попросить кого-то тебе с этим помочь?

**Comment by infotanka** [comment]
Переоткрой, пожалуйста, этот пункт, а лучше выдай мне права на Reopen.

**Comment by alec-c4** [comment]
Илья, если я пришлю документ в xml-формате в виде

```
    <region name="name" id="123">
      <tik name="name" id="1" />
      <tik name="name" id="2" />
      <tik name="name" id="3" />
     </region>
```

ты сможешь его загрузить в приложение и в дальнейшем отправлять на сервер? Или в каком виде тебе лучше прислать?

**Comment by xfyre** [comment]
лучше всего в виде Apple plist
но ты же вряд ли умеешь его делать?

**Comment by alec-c4** [comment]
Xcode у меня есть ;) постараюсь сделать ;)

**Comment by xfyre** [comment]
Леша, забей уже на список избирательных округов и дай мне просто список регионов в том формате, в котором я просил.
