### ISSUE TITLE
Дублирование названия в списках

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#30]
На последнем уровне чеклистса сейчас дублируются названия предыдущего уровня. Это бросается в глаза и выглядит плохо.

90% невлезающих названий я пофикшу сокращением. Можно ли для остальных немного уменьшить текст? Я готова вручную подобрать.

Пожалуйста, давай уберём эти названия сверху.

**Comment by xfyre** [comment]
вообще не понял о чем речь

**Comment by infotanka** [comment]
Заходишь в чеклисте на последний уровень, а там в тайтле «Урны» и
сразу после этого на странице «Урны».

2012/2/19 Ilya Obshadko
reply@reply.github.com:

**Comment by xfyre** [comment]
тогда лучше из тайтла убрать - в него все равно половина надписей не влезает

**Comment by infotanka** [comment]
Подписи будут короче. Убери, пожалуйста, снизу.

2012/2/19 Ilya Obshadko
reply@reply.github.com:

**Comment by xfyre** [comment]
Таня, ты эти подписи вообще видела? Не все из них можно сделать короче. После напильника в тайтлбаре удалось сделать более приемлемый шрифт и вроде бы все влезает, дублирующее убрал.

**Comment by infotanka** [comment]
Спасибо!

Не все, но 90% можно укоротить.

2012/2/19 Ilya Obshadko
reply@reply.github.com:
