### ISSUE TITLE
Экран «СОС»

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#31]
Давай оформим пока как текст с жалобой.

Если вас удаляют:
1. Попросите объяснить, чем конкретно вы "препятствуете работе" комиссии
2. Получите письменное решение комиссии со ссылкой на пункт закона о выборах и печатью комиссии
3. Добейтесь составления акта об административном правонарушении
4. Помните, если вы член комиссии, вас не имеют право удалить, только отстранить от работы
5. Если вас удалили, сообщите об этом нам. 

И далее сообщение, фото, видео и кнопка «Сообщить об удалении».

**Comment by xfyre** [comment]
это выглядит при имплементации "впрямую" совершенно жутко, текст занимает почти половину экрана

нужно придумать как сделать аккуратно

**Comment by xfyre** [comment]
пока оставил как есть

переделывать буду при наличии нормального дизайна

**Comment by infotanka** [comment]
Два варианта:

(Меня удаляют. Что делать? →) (Экран с инструкциями)
Сообщение
Фото
Видео
«Сообщить об удалении»

либо

Инструкции
(Отправить сигнал в штаб →) (Экран с контролами)

Сделай, как проще и как считаешь правильным. По мне: и так, и так — ок.
