### ISSUE TITLE
Заголовок «СОС»

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#32]
Давай напишем в заголовке «Меня удаляют». Это будет более понятно и правильно.

Если критично повторить то, что написано на таббаре, давай тогда просто «S.O.S.» без номера участка. Сейчас из-за большого количества знаков препинания вся конструкция привлекает слишком много внимания.

**Comment by xfyre** [comment]
а мы уверены в том, что SOS - это только удаление?

**Comment by infotanka** [comment]
Да. ВСю дорогу говорили только об этом сценарии.

2012/2/19 Ilya Obshadko
reply@reply.github.com:
