### ISSUE TITLE
Шарилки в отчёте

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#35]
В отчёт перед жалобой нужно добавить шарилки соц-сетей. Формат отчётов предлагаю проработать чуть позже, пока просто нужно сделать возможность отправить на фб, вк и твиттер ссылку на отчёт ленту этого пользователя у нас на сайте.

**Comment by infotanka** [comment]
Как если бы мы просто старинцу залайкали.

**Comment by xfyre** [comment]
мне нужно иметь для этого формат ссылки на страницу

**Comment by infotanka** [comment]
Поставь пока ссылку на яндекс, как только будут странички — заменим урл.

On 19 February 2012 14:24, Ilya Obshadko
reply@reply.github.com
wrote:

**Comment by infotanka** [comment]
Нужно будет добавить шарилки вместе со ссылкой на отчёт: https://progress-engine.basecamphq.com/projects/8732853/posts/57139902/comments#162212758

**Comment by xfyre** [comment]
готово
