### ISSUE TITLE
Первый экран

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#37]
Загрузила чуть поправленную версию в последний комментарий: https://progress-engine.basecamphq.com/projects/8732853/posts/57139902/comments#162175309

Поля ни в коем случае нельзя уносить на соседний экран. От этого сильно страдает наглядность и логика. Это могло бы быть мелочью внутри, но это наш первый экран. На нём нет мелочей.

**Comment by infotanka** [comment]
Комментарий с последней версией: https://progress-engine.basecamphq.com/projects/8732853/posts/57139902/comments#162178622

**Comment by xfyre** [comment]
Оставляем нынешний лейаут, статус наблюдателя я только причешу. С учетом телефона и отчества (которое тоже нужно) - все это в первый экран не влезает никак.

**Comment by infotanka** [comment]
Что ты планируешь сделать с полем id пользователя, которое занимает пол-экрана, и совершенно бесполезно для пользователя?

Как подскажешь пользователю, что нужно заполнить телефон, если его не удалось вытянуть? 

Где покажешь статус?

**Comment by infotanka** [comment]
Проблему с невлезанием можно решить, но я не вижу смысла этим заниматься, если у тебя всё равно нет возможности переделать первый экран.

**Comment by xfyre** [comment]
поле ID уже убрано и заменено на статус наблюдателя
на текущий момент это выглядит примерно вот так:

https://img.skitch.com/20120221-twfbxg33dfwrbet6kkejytkumr.png

**Comment by infotanka** [comment]
Не видно, какой статус. Это голосующий, член или пресса?

**Comment by infotanka** [comment]
Как понять, вошла я через твиттер или нет?

**Comment by xfyre** [comment]
у тебя логин появляется справа

статусы, чтобы их вменяемо писать, нужно сначала научиться отдавать с сервера - пока этого даже близко нет

**Comment by infotanka** [comment]
Не поняла про статусы. Пользователь сам не может указать кто он, или как?

Ты не ответил про телефон.

**Comment by xfyre** [comment]
телефон вводится в том же экране ввода персональной информации, что и все остальное

**Comment by xfyre** [comment]
да, и собственно экран ввода персональной информации можно легко разбить на секции и в заголовках секций уже написать зачем мы спрашиваем емейл и телефон

**Comment by infotanka** [comment]
Я имею в виду, как ты подскажешь пользователю, что телефон нужно заполнить?

**Comment by infotanka** [comment]
Нельзя ли спрятать фото на экран с уточнением статуса? Оно же далеко не всем нужно.

**Comment by xfyre** [comment]
пользователь в любом случае ткнется в эту кнопку, она на самом видном месте

а в экране с персональными данными будет необходимое пояснение

про уточнение статуса я пока не понимаю как оно будет работать вообще, так что не трогаем этот вопрос
