### ISSUE TITLE
Редактирование участков

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/watcher-ios#42]
В приложении отсутствует возможность редактировать или удалять участок. Это неудобно, если пользователь случайно ошибся при вводе данных

**Comment by xfyre** [comment]
Я сделал возможность удаления, возможности редактирования пока не будет. Тут, однако, будет множество вопросов - можно ли удалять участок по которому уже есть отметки, зависит ли это от статуса синхронизации отметок, и т.п.
