### ISSUE TITLE
Сообщать на сервер об удалении медиа-файла

### ISSUE THREAD

**Issue by nebolsin** [webnabludatel/watcher-ios#43]
URL: `/api/v1/messages/#{message_id}/media_items/#{id}.json?digest=#{digest}`
Method: `PUT`
POST-data: `device_id=982251d62e43ca542d5cb475b15c94774b63fab0&payload={…}`

В URL-e `message_id` — это айди пункта чеклиста, а `id` — это айди медиа-файла, который возвращается сервером при его создании.

Payload:

```
{
  "delete": true,
  "timestamp": время удаления медиа-файла с устройства
}
```

Result: `{"status":"ok", media_item_id: id удаленного медиа-файла}`

**Comment by aefimov** [comment]
PUT умышленно вместо DELETE?

**Comment by nebolsin** [comment]
Ага. Во-первых, файлик мы не удаляем, а помечаем как удаленный. Во-вторых, при DELETE-запросе не положено слать body, а значит нам нечего подписывать и пришлось бы конкретно для этого API-метода переделывать способ авторизации.

**Comment by aefimov** [comment]
Ясно :) Илья О сказал что он это не имплементил, сервер это тоже не поддерживает :)

**Comment by nebolsin** [comment]
Да, я не успел еще это реализовать, но это недолго совсем.

**Comment by xfyre** [comment]
Серега, тогда пока тебе, сделаешь - переводи обратно

**Comment by xfyre** [comment]
У меня есть на этом месте некая серьезная проблема с консистентностью происходящего. Core Data - это ORM, который полностью изолирует API от БД. Удаление MediaItem должно происходить следующим образом:

1) индикация удаления

```
    [self.checklistItem removeMediaItemsObject: mediaItem];
    [self.checklistItem setSynchronized: [NSNumber numberWithBool: NO]];
    [mediaItem setSynchronized: [NSNumber numberWithBool: NO]];
    [mediaItem setTimestamp: [NSDate date]];
    [appDelegate.managedObjectContext save: &error];
```

2) синхронизация изменений на сервер:
    - отправка измененного ChecklistItem
    - отправка информации об удаленном MediaItem

3) после успешной синхронизации на сервер - удаление MediaItem из backend storage

проблема в том, что на шаге (2) информация о связи ChecklistItem <-> MediaItem уже отсутствует, и я не могу использовать в запросе ни server_record_id от ChecklistItem, ни checklist_item_internal_id

нужно переделать API так, чтобы они были не нужны

**Comment by xfyre** [comment]
все готово
