### ISSUE TITLE
Прислать исправленный чеклист

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/watcher-ios#45]
Таня, Илья Сегалович заметил ошибки в чеклисте, которые ошибками как таковыми не являются и отдельно обещал их прислать утром. Ты будешь в копии, скорректируй плиз по его комментариям и пришли Илье Обшадко.

**Comment by xfyre** [comment]
у меня вчерашняя (видимо правильная) версия была не включена в последний билд
исправлено

**Comment by infotanka** [comment]
Илья, я обновила ещё раз: https://progress-engine.basecamphq.com/projects/8732853/posts/57139902/comments#comment_162438491
