### ISSUE TITLE
Индикатор статуса и отгрузка данных

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/watcher-ios#46]
1 - при загрузке картинки в процессе отправке на сервер переключаюсь на другой экран - индикатор сбрасывается на "ок", возвращаюсь на предыдущий - тоже самое. Не исключено, что орывается закачка данных

2 - Не очень информативен. Можно ли показывать количество неотправленных файлов, если не догужено и выделять красным цветом и если все ок - то показывать галочку заленым?

3 - Из экрана SOS при нажатии "отправить" - данные не отправляются сразу

**Comment by xfyre** [comment]
с индикатором вообще все плохо, он в текущем виде к употреблению непригоден чисто визуально
нужны альтернативные варианты

закачка данных не срывается, просто с индикацией проблемы

**Comment by xfyre** [comment]
синхронизацию состояния загрузки с состоянием индикатора я починил, по внешнему виду с Таней решим
