### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/watcher-ios#48]
Нет возможности повторно отправить сигнал SOS из приложения

**Comment by xfyre** [comment]
там кнопка SOS вообще играет декоративную роль пока, поскольку логика этого экрана мне неясна совершенно

**Comment by infotanka** [comment]
Два варианта:

(Меня удаляют. Что делать? →) (Экран с инструкциями)
Сообщение
Фото
Видео
«Сообщить об удалении»

либо

Инструкции
(Отправить сигнал в штаб →) (Экран с контролами)

Сделай, как проще и как считаешь правильным. По мне: и так, и так — ок.

**Comment by xfyre** [comment]
сделано
только текст для инструкций дайте нормальный вместо того что там сейчас будет

**Comment by infotanka** [comment]
Текст: 
1. Попросите объяснить, чем конкретно вы "препятствуете работе" комиссии
2. Получите письменное решение комиссии со ссылкой на пункт закона о выборах и печатью комиссии
3. Добейтесь составления акта об административном правонарушении
4. Помните, если вы член комиссии, вас не имеют право удалить, только отстранить от работы
5. Если вас удалили, сообщите об этом нам.
