### ISSUE TITLE
Формулировки

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#5]
Убрать в формулировках вопросительные знаки, они не нужны. Мы формулируем утеврждение, а пользователь с ним соглашается или нет.

Вопросы с «Есть ли» в оформлении участка нужно сформулировать как мы обсуждали в бэйскемпе «Увеличенная форма протокола (есть-нет)»

**Comment by xfyre** [comment]
Давайте я просто перед выпуском дам XML с описанием кому-то, кто умеет пользоваться текстовым редактором, и все формулировки будут поправлены как надо?

**Comment by xfyre** [comment]
решено
