### ISSUE TITLE
SOS again

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/watcher-ios#50]
При включенном авиарежиме нажимаем отправить SOS - показывается "отправляется", сообщение разумеется не уходит, но нотификации никакой нет об отсутствии связи.

**Comment by xfyre** [comment]
а иконка в тулбаре разве не меняется?

**Comment by alec-c4** [comment]
неа - да и надо имхо показывать сообщение, а то пользователь не поймет что к чему. не будет же он в экстренной ситуации рассматриватьсмену иконки

**Comment by xfyre** [comment]
а оно надо, подумай сам?

ну сказали мы юзеру "нет связи", он сказал "спасибо, кэп"
вместе с тем его выгнали на мороз, у него появился gprs, через 5 минут все спокойно отправилось

лишняя суета ни к чему

**Comment by alec-c4** [comment]
неочевидно и неюзабельно - надо его предупредить, иначе не поймет. Надо сказать, что инфа будет отправлена позже когда будет инет. А вообще неоднократно была ситуация, когда связь вроде бы должна быть, а ее нет и помогал только ребут :(

**Comment by xfyre** [comment]
последний комментарий не понял, подробнее плиз

**Comment by alec-c4** [comment]
Если человек в критической ситуации такой как удаление с участка отправит запрос о помощи и не увидит статуса - это не очень хорошо. У меня и еще у ряда людей была такая ситуация - вроде как есть голосовая связь, а доступа в интернет нет, приходилось перегружать телефон.

**Comment by xfyre** [comment]
с этим вроде решили
