### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/watcher-ios#51]
На экране регистрации пользователя есть возможность указать телефон. Его можно использовать при отправке SOS,  но данные могут быть неверными. Есть варианты
- При отправке SOS показывать номер и просить подтвердить что он корректный, если номера нет - показывать окно для его ввода
- Проверять номер через смс, как предложил Арсен Казибеков

Идем?

**Comment by xfyre** [comment]
есть еще вариант "пользователь дятел и сам виноват", по-моему он идеальный :)

**Comment by xfyre** [comment]
в общем и целом корректный механизм верификации - это отдельное серьезное приключение, на которое у нас нет времени

**Comment by xfyre** [comment]
зарываю, не будем делать
