### ISSUE TITLE
Ошибки в WatcherChecklist.plist

### ISSUE THREAD

**Issue by suntehnik** [webnabludatel/watcher-ios#52]
Ключ чеклиста: absentee_vote_voters_not_in_registry
значение lo_value = false
 а должно быть наоборот lo_value=true
hi_value должно иметь значение false

 аналогично c ключем absentee_vote_akt_after_returning

Ключ чеклиста: absentee_vote_registry_is_correct
формулировка: 
<string>Реестр заполнен правильно: указаны ФИО, что ещё нужно?</string>
Не уверен что она должна быть именно такой

Опечатка в названии ключа: abstentee_vote_registry_is_valid

Проверь что исправил 
Ключ koib_nonelectricity_problem
"Другие сбои в работе КОИБов"

 hi_text должен быть "да"

последние два раздела не забивал - соответственно не проверял

**Comment by xfyre** [comment]
нет, неверно

нарушение оно или нет - определяется полем violationFlag

```
        if ( [self.checklistItem.value isEqualToString: [switchOptions objectForKey: @"lo_value"]] )
            self.checklistItem.violationFlag = [NSNumber numberWithInt: 0];
        else if ( [self.checklistItem.value isEqualToString: [switchOptions objectForKey: @"hi_value"]] )
            self.checklistItem.violationFlag = [NSNumber numberWithInt: 1];
        else
            self.checklistItem.violationFlag = nil;
```

а true/false - это всегда, во всех случаях ответ на вопрос

нужно эту логику еще раз перепроверить по всему чеклисту
все прочее поправил
