### ISSUE TITLE
Переключалка на Общий отчет с сервера на экране «Отчет»

### ISSUE THREAD

**Issue by aefimov** [webnabludatel/watcher-ios#61]
Возможность показывать отчет с сервера, который показывается на сайте. Нужно пробросить heartbeat ручку в серверном API.

**Comment by xfyre** [comment]
смысла этого реквеста я вообще не понял
давайте не будем писать в трекер что попало

**Comment by aefimov** [comment]
Смысл в том, чтобы пользователь видел каку-то статистику по себе с сервера (что он отправил на сервер, что сервер вооще знает) https://github.com/webnabludatel/webnabludatel_server/issues/3

Так как у нас фоновая загрузка, то вообще не понятно, какие фотки загрузились, а какие нет. Какие видео загрузились.
