### ISSUE TITLE
Не удалять введенное сообщение в SOS при выборе Фотки и Видео

### ISSUE THREAD

**Issue by aefimov** [webnabludatel/watcher-ios#62]
Если на экране SOS написать сообщение а потом выбрать фотку, то сообщение стирается и его приходится писать заново.

**Comment by xfyre** [comment]
это тестировалось сотню раз и не вопроизводится вообще

**Comment by aefimov** [comment]
Вводишь сообщение, не трогая кнопку Done, жмешь выбрать фотку. Сообщение пропадает.

**Comment by aefimov** [comment]
Если нажать на Done, то все ок.
