### ISSUE TITLE
Аномальная сетевая активность на загрузке фото удостоверения

### ISSUE THREAD

**Issue by aefimov** [webnabludatel/watcher-ios#65]
Воспроизводится так, удаляем приложение, ставим по-новой, запускаем ждем когда отрисует галку на первом экране в поле с надписью "Регистрация в системе...". Ждем 20 секунд. Затем выбираем "Фото удостоверения". После этого крутилка сетевой активности будут быстро мигать и вместе с этим будет мигать красная иконка.

**Comment by xfyre** [comment]
мы выяснили, что это ошибка авторизации
почему она имеет место - нужно на сервере смотреть

у меня в таких же условиях все работает идеально

**Comment by aefimov** [comment]
1. На POST media_item.json прилетает 401 с {"error":"Вы должны подтвердить вашу учётную запись."}
2. Клиентне должен досить сервер в этом случае, а по логу шло 5 запросов в секунду
3. Красную иконку мне кажется надо убрать вообще :)

**Comment by xfyre** [comment]
я так понимаю что со всем уже разобрались
повторную попытку отправки мы теперь делаем через интервал
