### ISSUE TITLE
Правки плистов

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#66]
«Я»: Давайте напишем «Фото удостоверения» на кнопке, а фразу «Загрузить фото удостоверения» уберём.

«Наблюдение»: в состоянии участка, увеличенная форма протокола, ответы должны быть «нет-есть» вместо «нет-да». Надпись «Фото книг без персональных данных» сократить до «Фото книг без персон. данных»

«СОС»: Надписи на кнопках должны быть «Фото» и «Видео».

Я могу всё поправить сама, но тогда мне нужны соответсвующие файлы.

**Comment by xfyre** [comment]
сделал все кроме первого
