### ISSUE TITLE
В правом верхнем углу нужно добавить индикатор

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#7]
В правом верхнем углу нужно добавить индикатор: https://progress-engine.basecamphq.com/projects/8732853/posts/57139902/comments#comment_159653629 (он будет счётчиком дней до выборов перед началом, и индиктором заполнения в день выборов). По клике на него пусть открвается экран с отчётами, на нём до выборов будет текст: «До выборов осталось 5 дней. Пока приложение работатет в тестовом режиме, 4 марат здесь появятся отчёт о замеченных вами нарушениях».

**Comment by xfyre** [comment]
- по ссылке у меня ничего релевантного не открывается
- экран с отчетами - это третий экран?

**Comment by infotanka** [comment]
В верхнем правом углу есть некий индиктор, который работает так:
до выборов показывает количество дней до выборов, по клику выводит надпись:
До выборов осталось
<крупно>14<крупно>
дней.

Пока приложение работет в тестовом режиме и данные не сохраняются.

После начала выборов, индикатор будет показывать моменты синхронизации с сервером (обычная крутилка) и результат (галочку если ок, крестик если проблемы). По клику можно показывать историю синхронизаций.

Важно. Эту функциональность можно добавить уже после отправки в аппстор, как апдэйт.

**Comment by infotanka** [comment]
До выборов будет выглядеть примерно так: https://progress-engine.basecamphq.com/projects/8732853/file/110781584/screen_all_10.png

**Comment by xfyre** [comment]
не получается консистентной картины

ты предлагаешь складывать на один и тот же контрол совершенно разные по смыслу вещи
если этот контрол у нас - статус синхронизации, то именно он там и должен быть
тем более, что синхронизация будет работать с того момента, как она будет реализована (и это правильно - люди смогут тестировать приложение полноценно)

так что оставлю вариант галочка/воскл.знак/спиннер

**Comment by infotanka** [comment]
Хорошо, давай пока там. Про тестовый режим придумаю что-нибудь ещё.

**Comment by xfyre** [comment]
готово, релиз 0.2.3
