### ISSUE TITLE
Подсказки в полях

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#8]
Зачем мы дублируем все подписи подсказками в полях? Выглядит параноидально. Давайте уберём подписи, или хотя бы сделаем подсказки в виде «Иван Иванов».

**Comment by xfyre** [comment]
я так понимаю что исправлено в новом plist

**Comment by infotanka** [comment]
Илья, у меня не было plist для первого экрана. Дашь?

**Comment by xfyre** [comment]
без проблем
