### ISSUE TITLE
ФИО

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-ios#9]
Зачем мы разделяем поля «Имя» и «Фамилия»? Почему не сделать просто «ФИО»?

**Comment by xfyre** [comment]
чтобы индексировать и искать в БД потом проще было, например

**Comment by infotanka** [comment]
А зачем нам отдельно имя и фамилию индексировать? Зачем вообще индекс по этим полям?

**Comment by infotanka** [comment]
Я хочу сказать, что понимаю, как работают БД, и зачем значения в разные поля кладутся. 

Но это точно не наш случай.

**Comment by xfyre** [comment]
Нам - не знаю зачем, а на сервере может понадобиться. Давай не будем трогать, это непринципиально.

**Comment by infotanka** [comment]
Переоткрой, пожалуйста.

**Comment by infotanka** [comment]
Илья, это наш первый экран, на нём всё принципиально.

Давай либо обсудим с Тимофеем, зачем может понадобится такое разделение, либо просто объединим.

**Comment by xfyre** [comment]
Я сейчас вид этого первого экрана вообще поменяю принципиально - будет выбор способа регистрации первой секцией, и summary по статусу синхронизации второй секцией, ФИО/email вообще будет вводиться в модальном диалоге.

**Comment by infotanka** [comment]
Нет, Илья. Это очень плохое решение.

Не надо никакого выбора способа: только кнопки «твиттер», «фэйсбук» и два поля (ФИО и почта). И никаких модальных окон. Это грубейшее нарушение всех принципов нормлаьных интерфейсов.

**Comment by xfyre** [comment]
первый экран обсуждаем не здесь, в любом случае
ФИО пока не разделяем, жду макетов
